version: '3.1'
services: 
  web:
    restart: always
    build: .
    container_name: paulo-web
    volumes: 
      - ./:/var/www/
    # depends_on: 
    #   - db
    networks:
      - internal
  
  # db:
  #   image: postgres
  #   restart: always
  #   container_name: orcamento-db-usm
  #   ports:
  #     - "5442:5432"
  #   environment:
  #     POSTGRES_USER: laravel
  #     POSTGRES_PASSWORD: 123456
  #     POSTGRES_DB: laravel
  #   volumes: 
  #   - "./.docker/dbdata:/var/lib/postgresql/data"
  #   networks:
  #     - internal

  nginx:
    build: ./.docker/nginx
    restart: always
    container_name: paulo-nginx
    ports:
      - "9992:80"
    volumes: 
      - ./:/var/www
    depends_on: 
      - web
    networks:
      - internal
  
networks:
  internal:
    driver: bridge

